<dt>Vague</dt>
<dd><%wave.num%>/<%wave.max%></dd>
<dt>Difficulte</dt>
<dd><%rules.difficulty.text%></dd>
<dt>Joueurs</dt>
<dd><%rules.numplayers%>/<%rules.maxplayers%></dd>
<dt>Minimum pour commencer</dt>
<dd><%rules.minnetplayers%></dd>
<dt>Spectateurs</dt>
<dd><%rules.numspectators%>/<%rules.maxspectators%></dd>
<dt>Possibilitee de voter pour la carte</dt>
<dd><%rules.mapvote%></dd>
<dt>Possibilitee d'exclure un joueur</dt>
<dd><%rules.kickvote%></dd>
