<tr class="<%evenodd%>">
  <td class="right"><input type="checkbox" name="bot" value="<%player.playerkey%>" id="bot_<%player.playerid%>"/></td>
  <td style="background: <%player.teamcolor%>; color: <%player.teamcolor%>;"><%player.teamid%>&#160;</td>
  <td><label for="bot_<%player.playerid%>"><%player.name%></label></td>
  <td class="right"><%player.role%></td>
  <td class="right"><%player.score%></td>
  <td class="right"><%player.deaths%></td>
  <td class="right"><%player.kills%></td>
</tr>
