<div id="mleditor">
<table class="noborder">
<thead>
<tr>
    <th>Available Maps</th>
    <th>Map Cycle</th>
</tr>
</thead>

<tbody id="noscript">
<tr>
    <td><textarea rows="15" cols="30" id="allmaps" readonly="readonly"><%allmaps.plain%></textarea></td>
    <td><textarea rows="15" cols="30" name="mapcycle" id="mapcycle"><%cycle.plain%></textarea></td>
</tr>
</tbody>

</table>

<p id="noscriptHint"><em>Note:</em> you get the best map list editing experiance in a JavaScript capable browser. Enter one map per line, you can include URL options. Use the URL option <code>?RoundLimit=XX</code> to set the round limit for this specific map.</p>

</div>

<script type="text/javascript" src="/images/default_maplist_editor.js?gzip"></script>
