<style type="text/css">
	#fastnav{ position: absolute; top: 40px; left: 430px; }
	#fastnav a { margin-right: 6px; padding: 4px 6px; border: 1px solid #a5181a; text-decoration: none; }
	#fastnav a:hover{ background: #4c1111; }
</style>

<div id="fastnav"> // replace with your ip address as well as the webadmin port, you must trigger the ports in your router settings
  <a href="http://01.234.56.789:8080/ServerAdmin/current/info">Example 1</a>
  <a href="http://01.234.56.789:8081/ServerAdmin/current/info">Example 2</a>
  <a href="http://01.234.56.789:8082/ServerAdmin/current/info">Example 3</a>
  <a href="http://01.234.56.789:8083/ServerAdmin/current/info">Example 4</a>
  <a href="http://01.234.56.789:8084/ServerAdmin/current/info">Example 5</a>
</div>